services:

  app:
    build: .
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:18.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}