spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable&currentSchema=finance_management,public
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SECURITY_OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${SECURITY_OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/api/v1/auth/oauth2/callback/{registrationId}"

server:
  port: ${SERVER_PORT:8086}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}

app:
  security:
    base64-secret: ${SECURITY_JWT_BASE64_SECRET}
    access-token-expiry: ${SECURITY_ACCESS_TOKEN_EXPIRY}
    refresh-token-expiry: ${SECURITY_REFRESH_TOKEN_EXPIRY}

  bootstrap-admin:
    email: ${BOOTSTRAP_ADMIN_EMAIL}
    password: ${BOOTSTRAP_ADMIN_PASSWORD}

app-configuration-logger:
  enabled: true